# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'maxoucard_app' do
  platform :ios, '7.0'
  pod 'SDWebImage', '~>3.8'
  pod 'ChameleonFramework'
  pod 'AFNetworking', '~> 3.0'
  pod 'RESideMenu'
  pod 'SVProgressHUD'
  pod 'PocketSocket'
end

